# permissions for end users to view balancers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: balancer-viewer-role
rules:
- apiGroups:
  - exposer.hliangzhao.io
  resources:
  - balancers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - exposer.hliangzhao.io
  resources:
  - balancers/status
  verbs:
  - get
